# Generated by Django 4.1.7 on 2023-03-07 08:41

# django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("gdp", models.CharField(max_length=100)),
                ("population", models.CharField(max_length=20)),
                ("land_area", models.CharField(max_length=20)),
                ("waste_generated", models.CharField(max_length=20)),
            ],
        ),
    ]
