# Generated by Django 4.1.7 on 2023-03-08 10:34

# django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_userinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="country_code",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="country_flag",
            field=models.URLField(null=True),
        ),
    ]
