# Generated by Django 4.1.7 on 2023-03-09 08:40

# django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_country_country_code_country_country_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="investment_required",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="machines_required",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
