# Generated by Django 4.1.7 on 2023-03-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_country_investment_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="land_area_percent",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="population_percent",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
